#!/usr/bin/env bash
# Provision Cloudflare R2 for restic, from scripts. Creates the R2 bucket and derives
# S3 credentials from a Cloudflare API token, writing them into restic.env. Idempotent.
# The CF token is read from gitignored cf.env and is never logged or committed.
#
# Token needed (dash.cloudflare.com > My Profile > API Tokens > Create Token > Custom):
#   Permission: Account > Workers R2 Storage > Edit   (scoped to your account)
source "$(dirname "$0")/../lib/common.sh"

CFENV="${REPO_ROOT}/cf.env"
[ -f "${CFENV}" ] || { echo "missing ${CFENV} — cp cf.env.example cf.env and fill it" >&2; exit 1; }
set -a; . "${CFENV}"; set +a
: "${CF_API_TOKEN:?set CF_API_TOKEN in cf.env}"
: "${CF_ACCOUNT_ID:?set CF_ACCOUNT_ID in cf.env}"
BUCKET="${HERMES_BOX_R2_BUCKET:-hermes-box-backups}"
API="https://api.cloudflare.com/client/v4"
AUTH=(-H "Authorization: Bearer ${CF_API_TOKEN}")

echo "Verifying API token..."
vr="$(curl -fsS "${AUTH[@]}" "${API}/user/tokens/verify")" || { echo "token verify request failed" >&2; exit 1; }
echo "${vr}" | jq -e '.success' >/dev/null || { echo "token invalid: $(echo "$vr" | jq -c .errors)" >&2; exit 1; }
TOKEN_ID="$(echo "${vr}" | jq -r '.result.id')"
[ -n "${TOKEN_ID}" ] && [ "${TOKEN_ID}" != "null" ] || { echo "could not read token id" >&2; exit 1; }
echo "  token active (id ${TOKEN_ID:0:8}…)"

echo "Creating R2 bucket '${BUCKET}' (idempotent)..."
cr="$(curl -fsS "${AUTH[@]}" -H 'Content-Type: application/json' \
        -X POST "${API}/accounts/${CF_ACCOUNT_ID}/r2/buckets" \
        --data "{\"name\":\"${BUCKET}\"}" 2>/dev/null || true)"
if echo "${cr}" | jq -e '.success==true' >/dev/null 2>&1; then
  echo "  bucket created"
elif echo "${cr}" | jq -e '.errors[]? | (.message|test("exist";"i"))' >/dev/null 2>&1; then
  echo "  bucket already exists"
else
  echo "  note: $(echo "${cr}" | jq -c '.errors // .messages // .' 2>/dev/null)"
fi

# Derive S3 credentials (Cloudflare R2 token convention: AKID = token id, secret = sha256(value)).
AKID="${TOKEN_ID}"
SECRET="$(printf '%s' "${CF_API_TOKEN}" | shasum -a 256 | cut -d' ' -f1)"
REPO="s3:https://${CF_ACCOUNT_ID}.r2.cloudflarestorage.com/${BUCKET}"

# Preserve an existing restic password (don't break an already-initialized repo); else generate.
PW=""
[ -f "${REPO_ROOT}/restic.env" ] && PW="$(grep -E '^RESTIC_PASSWORD=' "${REPO_ROOT}/restic.env" 2>/dev/null | head -1 | cut -d= -f2-)"
case "${PW}" in ""|*CHANGE_ME*) PW="$(openssl rand -base64 36 | tr -d '\n')"; echo "  generated a new RESTIC_PASSWORD (save it!)";; *) echo "  kept existing RESTIC_PASSWORD";; esac

umask 077
cat > "${REPO_ROOT}/restic.env" <<EOF
# Generated by scripts/cf-r2-setup.sh — gitignored. SAVE RESTIC_PASSWORD somewhere safe.
RESTIC_REPOSITORY=${REPO}
RESTIC_PASSWORD=${PW}
AWS_ACCESS_KEY_ID=${AKID}
AWS_SECRET_ACCESS_KEY=${SECRET}
AWS_DEFAULT_REGION=auto
EOF
echo "Wrote ${REPO_ROOT}/restic.env  (repo: ${REPO})"
echo "Next: ./scripts/restic-backup.sh"
